version: '3.8'
services:
  nextjs:
    build: .
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env

  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=187.77.168.241
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://187.77.168.241:5678/
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
